### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by zek** [k3kaimu/awebview#3]
I dont know why but it gives error

Running post-generate commands for awebview...
## std.process.ProcessException@std\process.d(560): Failed to spawn new process (The system cannot find the file specified.)

0x00445376
0x0043D27E
0x004310CA
0x0041C6A6
0x00405B8A
0x004043FA
0x00409A06
0x004099DB
0x004098F3
0x00404577
0x75177C04 in BaseThreadInitThunk
0x7734AD1F in RtlInitializeExceptionChain
0x7734ACEA in RtlInitializeExceptionChain
Error executing command generate:
Command failed with exit code 1
Error executing command run:
Command failed with exit code 2

**Comment by k3komatsu** [comment]
Please tell me what your environment.
Now, awebview supports windows only..., but OS X and Linux will be supported in the near future.

**Comment by zek** [comment]
Windows 8.1 64bit

**Comment by k3komatsu** [comment]
I'm developing awebview on Windows Server 2012 R2(64bit) and Windows 7(64bit).
So I think that it is very strange.

Sorry, Could you tell me version of dub and dmd, and update them.
I use dmd v2.067.0 and dub v0.9.22.

**Comment by k3komatsu** [comment]
In post-generate phase, dub will execute command `dub generate --config=copyCommand visuald` and `dub generate --config=postCopyCommand visuald`, so please check the Path of  windows environment variables.

**Comment by zek** [comment]
dub 0.9.23
DMD 2.067.1
windows 8.1 64 bit

**Comment by zek** [comment]
Yes I was forget to add to path. But this time it throws
Fatal error: unable to open input file 'string'
--- errorlevel 1

**Comment by k3komatsu** [comment]
Sorry, I forgot to tell you about dmc(Digital Mars C++ Compiler).

You can download it on http://www.digitalmars.com/download/freecompiler.html , and unzip to `C:\DMC\dm`.
And you should add path also.

DMC is not support C++ STL.
So you should download STLport on http://www.digitalmars.com/download/freecompiler.html , and unzip to `C:\DMC\dm\stlport`.
Next you need to rewrite `INCLUDE` of `C:\DMC\dm\bin\sc.ini` as follows.

```
INCLUDE="%@P%\..\stlport\stlport";"%@P%\..\include";"%@P%\..\mfc\include";%INCLUDE%
```

`"%@P%\..\stlport\stlport"` will be replaced to `C:\DMC\dm\strlport\stlport`.
`C:\DMC\dm\strlport\stlport` contain STLs such as `algorithm`, `cmath` and `string` etc.

Now you can use STL on DMC and you can build awebview by `dub` maybe.

**Comment by zek** [comment]
Yeah I guess Walter forget to add C++ STL to DMC :)

It works like a charm. Thank you.
