### ISSUE TITLE
dmd 2.068 beta1

### ISSUE THREAD

**Issue by Laeeth** [k3kaimu/awebview#4]
just fyi - think some problems with 2.068.  As well as pure / system, also not sure if it works on 64 bit as there are problems long vs int.  Laeeth.

source/awebview/jsvariable.d(40): Error: pure function 'awebview.jsvariable.jsExpression' cannot call impure function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/jsvariable.d(40): Error: safe function 'awebview.jsvariable.jsExpression' cannot call system function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/jsvariable.d(50): Error: pure function 'awebview.jsvariable.jsExpression' cannot call impure function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/jsvariable.d(50): Error: safe function 'awebview.jsvariable.jsExpression' cannot call system function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/jsvariable.d(40): Error: pure function 'awebview.jsvariable.jsExpression' cannot call impure function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/jsvariable.d(40): Error: safe function 'awebview.jsvariable.jsExpression' cannot call system function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/jsvariable.d(50): Error: pure function 'awebview.jsvariable.jsExpression' cannot call impure function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/jsvariable.d(50): Error: safe function 'awebview.jsvariable.jsExpression' cannot call system function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/jsvariable.d(40): Error: pure function 'awebview.jsvariable.jsExpression' cannot call impure function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/jsvariable.d(40): Error: safe function 'awebview.jsvariable.jsExpression' cannot call system function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/jsvariable.d(50): Error: pure function 'awebview.jsvariable.jsExpression' cannot call impure function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/jsvariable.d(50): Error: safe function 'awebview.jsvariable.jsExpression' cannot call system function 'awebview.wrapper.jsvalue.JSValue.~this'
source/awebview/gui/html.d(1072): Error: template instance awebview.gui.html.querySelectorImpl!true error instantiating
source/awebview/sound.d(220): Error: function pointer SDL_RWFromConstMem (const(void)_, int) is not callable using argument types (const(void)_, ulong)
source/awebview/sound.d(67): Error: template instance awebview.sound.SDLMixer.callCLib!(SDL_RWFromConstMem, const(void)*, ulong) error instantiating
source/awebview/sound.d(375): Error: function awebview.sound.SoundChannel.onAttachToChannel (int id) is not callable using argument types (ulong)
source/awebview/sound.d(385): Error: function awebview.sound.SoundChannel.onAttachToChannel (int id) is not callable using argument types (immutable(ulong))
FAIL .dub/build/library-debug-linux.posix-x86_64-dmd_2068-A2368F13869440EE8BE2C353A143DD0A/ awebview staticLibrary
Error executing command build:
dmd failed with exit code 1.
[laeeth@fedorabox awebview]$ ^C

**Comment by k3komatsu** [comment]
Sorry, this library supports windows(x86) only now.
I will support other OS and 64bit environment soon.

**Comment by Laeeth** [comment]
Thanks a lot.  Laeeth
